name: V2Ray Android Custom Setup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
      - name: تحميل V2Ray
        run: |
          powershell -Command "Invoke-WebRequest -Uri 'https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-windows-64.zip' -OutFile 'v2ray.zip'"
          powershell -Command "Expand-Archive 'v2ray.zip' -DestinationPath 'C:\v2ray' -Force"

      - name: إعداد config.json
        run: |
          echo '{
            "inbounds":[
              {
                "listen":"0.0.0.0",
                "port":1080,
                "protocol":"socks",
                "settings":{"auth":"noauth","udp":true}
              }
            ],
            "outbounds":[{"protocol":"freedom"}],
            "log":{"loglevel":"warning"}
          }' > C:\v2ray\config.json

      - name: فتح البورت في الجدار الناري
        run: |
          New-NetFirewallRule -DisplayName "V2Ray Port 1080" -Direction Inbound -LocalPort 1080 -Protocol TCP -Action Allow
          New-NetFirewallRule -DisplayName "V2Ray Port 1080 UDP" -Direction Inbound -LocalPort 1080 -Protocol UDP -Action Allow

      - name: تشغيل V2Ray
        run: |
          Start-Process "C:\v2ray\v2ray.exe" -ArgumentList "run","-config","C:\v2ray\config.json"
